// scripts/makeManifest.cjs
const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'public', 'portfolio');

// Dodaj kategorije koje zaista postoje kod tebe (možeš slobodno obrisati one koje nemaš)
const CATS = [
  'vencanje', 'svadbe', 'portret', 'studio',
  'rodjendani', 'krstenja', 'crno-belo',
];

const ALLOWED = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif']);

function listFilesSafe(dir) {
  try {
    return fs.readdirSync(dir, { withFileTypes: true })
      .filter(d => d.isFile())
      .map(d => d.name)
      .filter(name => ALLOWED.has(path.extname(name).toLowerCase()))
      .sort((a, b) => a.localeCompare(b, 'sr'));
  } catch {
    return [];
  }
}

const manifest = {};
for (const cat of CATS) {
  const full = path.join(PUBLIC_DIR, cat);
  if (fs.existsSync(full)) manifest[cat] = listFilesSafe(full);
}

const outFile = path.join(ROOT, 'src', 'data', 'portfolioManifest.ts');
const file = `// ⚠️ AUTO-GENERATED by scripts/makeManifest.cjs — ne menjaj ručno
export const PORTFOLIO_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;
export type PortfolioCat = keyof typeof PORTFOLIO_MANIFEST;
`;
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, file, 'utf8');

console.log('✅ Manifest generisan:', outFile);
for (const [cat, arr] of Object.entries(manifest)) {
  // VAŽNO: ovde su PRAVI backtickovi bez kosih crta
  console.log(`  - ${cat}: ${arr.length} fajlova`);
}