// ⚠️ AUTO-GENERATED by scripts/makeCldManifest.cjs — ne menjaj ručno
export const PORTFOLIO_MANIFEST = {
  "vencanje": [
    "p1_csyt6w",
    "p10_mqsxjz",
    "p11_vkrakw",
    "p12_kxjj4n",
    "p13_gvxgp6",
    "p6_r14vwu"
  ],
  "svadbe": [
    "p6_bmvj8g",
    "p7_wwb5gb",
    "p8_ymhqil"
  ],
  "studio": [
    "p10_x5rape",
    "p11_atcasg",
    "p12_ghfcsr",
    "p13_udmxnu",
    "p14_aijic6",
    "p16_kd50f2",
    "p18_thc3ta",
    "p19_fq31jh",
    "p2_tixtkq",
    "p20_txjxht",
    "p21_x6dcnp",
    "p22_vmkumq",
    "p23_ltoicd",
    "p24_euhs0o",
    "p32_ptksbq",
    "p4_l4wfqj",
    "p7_xzwhy1",
    "p8_cr1ev3"
  ],
  "rodjendani": [
    "p10_osxphb",
    "p11_mgfpf0",
    "p12_i2zv5b",
    "p13_vwwr8e",
    "p14_utwan7",
    "p23_rdl57s",
    "p25_byd0uy",
    "p26_s5i1t4",
    "p28_wrelzv",
    "p30_vrzkqa",
    "p31_elfl5s",
    "p35_wzjlg6",
    "p36_hze2ro",
    "p48_qndiih",
    "p49_ttlb9a",
    "p9_k5kbiv"
  ],
  "krstenja": [
    "p1_ckicb4",
    "p10_oaa4uj",
    "p11_kiachw",
    "p12_yic4ui",
    "p13_vwyxqj",
    "p14_mlat3g",
    "p15_h4mjjl",
    "p16_y2wcew",
    "p18_hwvzh6",
    "p2_dafbll",
    "p3_ejx9rs",
    "p4_ejg3ic",
    "p5_pjsdgj",
    "p6_l5g4nv",
    "p8_tikaxx",
    "p9_g4xnca"
  ],
  "crno-belo": [
    "p10_l1oek9",
    "p11_uhkfcl",
    "p12_kfsf6g",
    "p13_hjceqe",
    "p14_pywzrc",
    "p4_ucjuao",
    "p5_syanae",
    "p6_upi9kw",
    "p7_x7yv61",
    "p8_fne2zy",
    "p9_kw3uai"
  ]
} as const;
export type PortfolioCat = keyof typeof PORTFOLIO_MANIFEST;
export type PortfolioId = typeof PORTFOLIO_MANIFEST[PortfolioCat][number];
